/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_basica(char *host, float primernumero, float segundonumero, char operador)
{
	CLIENT *clnt;
	float  *result;


#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_SIMPLE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (operador){
		case '+':
			result = sumar_1(primernumero,segundonumero, clnt);
			break;
		case '-':
			result = restar_1(primernumero,segundonumero,clnt);
			break;
		case 'x':
			result = multiplicar_1(primernumero,segundonumero,clnt);
			break;
		case '/':
			result = dividir_1(primernumero,segundonumero,clnt);
			break;
		default:
            printf("Operador no válido.\n");
            result = NULL;
            break;
	}

	if(result == (float *)NULL){
		clnt_perror(clnt, "call failed");
		exit(1);
	}

	printf("EL RESULTADO CALCULADO ES: %f\n", *result);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int operador_valido(char operador, const char *operadores, int tam)
{
	int resultado = 0;

	for (int i = 0; i < tam && resultado == 0; i++)
	{
		if (operador == operadores[i])
			resultado = 1;
	}

	return resultado;
}


int
main (int argc, char *argv[])
{
	char *host;


	host = argv[1];
	system("Clear");

	printf("Los operadores válidos son: + - x /\n");
	printf("Escriba la expresión como de la siguiente manera --> <numero1> <operador> <numero2>\n");

	float primernumero = 0.0f, segundonumero = 0.0f, resultado = 0.0f;
	const char operadores[operadores_basicos] = {'+', '-','x','/'};
	char operador;

	do
		{
			scanf("%f %c %f", &primernumero, &operador, &segundonumero);
			if (!operador_valido(operador, operadores, operadores_basicos))
			{
				printf("No se ha reconocido el operador introducido\n");
				printf("Los operadores válidos son: + - x /\n");
			}
		} while (!operador_valido(operador, operadores, operadores_basicos));

	calculadora_basica(host,primernumero,segundonumero, operador);

exit (0);
}
