/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
sumar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	result = a + b;

	return &result;
}

float *
restar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	result = a - b;

	return &result;
}

float *
multiplicar_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

	result = a * b;

	return &result;
}

float *
dividir_1_svc(float a, float b,  struct svc_req *rqstp)
{
	static float  result;

    if (b != 0) {
        result = a / b;
    } else {
        result = 0.0;
    }
	return &result;
}

VectorNode *
suma_vectores_2_svc(VectorNode VectorA, VectorNode VectorB, int longitud,  struct svc_req *rqstp)
{
	static VectorNode  result;

  	for(int i = 0; i < longitud; i++){
    	result.vector[i] = VectorA.vector[i] + VectorB.vector[i];
  	}

	return &result;
}


VectorNode *
resta_vectores_2_svc(VectorNode VectorA, VectorNode VectorB, int longitud,  struct svc_req *rqstp)
{
	static VectorNode  result;

  	for(int i = 0; i < longitud; i++){
    	result.vector[i] = VectorA.vector[i] - VectorB.vector[i];
  	}

   return &result;
}


float *
producto_escalar_2_svc(VectorNode VectorA, VectorNode VectorB, int longitud,  struct svc_req *rqstp)
{
	static float result;

  	for (int i = 0; i < longitud; i++){
    	result += VectorA.vector[i] * VectorB.vector[i];
  	}
	printf("Se mete");
	return &result;
}


VectorNode *
producto_vectores_2_svc(VectorNode VectorA, VectorNode VectorB, int longitud,  struct svc_req *rqstp)
{
	static VectorNode  result;

  	for (int i = 0; i < longitud; i++){
    	result.vector[i] = VectorA.vector[i] * VectorB.vector[i];
 	}

	return &result;
}