/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct VectorNode {
	float vector[20];
};
typedef struct VectorNode VectorNode;

typedef VectorNode *VectorList;

struct sumar_1_argument {
	float a;
	float b;
};
typedef struct sumar_1_argument sumar_1_argument;

struct restar_1_argument {
	float a;
	float b;
};
typedef struct restar_1_argument restar_1_argument;

struct multiplicar_1_argument {
	float a;
	float b;
};
typedef struct multiplicar_1_argument multiplicar_1_argument;

struct dividir_1_argument {
	float a;
	float b;
};
typedef struct dividir_1_argument dividir_1_argument;

struct suma_vectores_2_argument {
	VectorNode VectorA;
	VectorNode VectorB;
	int longitud;
};
typedef struct suma_vectores_2_argument suma_vectores_2_argument;

struct resta_vectores_2_argument {
	VectorNode VectorA;
	VectorNode VectorB;
	int longitud;
};
typedef struct resta_vectores_2_argument resta_vectores_2_argument;

struct producto_escalar_2_argument {
	VectorNode VectorA;
	VectorNode VectorB;
	int longitud;
};
typedef struct producto_escalar_2_argument producto_escalar_2_argument;

struct producto_vectores_2_argument {
	VectorNode VectorA;
	VectorNode VectorB;
	int longitud;
};
typedef struct producto_vectores_2_argument producto_vectores_2_argument;

#define CALCULADORA 0x20000004
#define CALCULADORA_SIMPLE 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR 1
extern  float * sumar_1(float , float , CLIENT *);
extern  float * sumar_1_svc(float , float , struct svc_req *);
#define RESTAR 2
extern  float * restar_1(float , float , CLIENT *);
extern  float * restar_1_svc(float , float , struct svc_req *);
#define MULTIPLICAR 3
extern  float * multiplicar_1(float , float , CLIENT *);
extern  float * multiplicar_1_svc(float , float , struct svc_req *);
#define DIVIDIR 4
extern  float * dividir_1(float , float , CLIENT *);
extern  float * dividir_1_svc(float , float , struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR 1
extern  float * sumar_1();
extern  float * sumar_1_svc();
#define RESTAR 2
extern  float * restar_1();
extern  float * restar_1_svc();
#define MULTIPLICAR 3
extern  float * multiplicar_1();
extern  float * multiplicar_1_svc();
#define DIVIDIR 4
extern  float * dividir_1();
extern  float * dividir_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */
#define CALCULADORA_VECTORES 2

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA_VECTORES 5
extern  VectorNode * suma_vectores_2(VectorNode , VectorNode , int , CLIENT *);
extern  VectorNode * suma_vectores_2_svc(VectorNode , VectorNode , int , struct svc_req *);
#define RESTA_VECTORES 6
extern  VectorNode * resta_vectores_2(VectorNode , VectorNode , int , CLIENT *);
extern  VectorNode * resta_vectores_2_svc(VectorNode , VectorNode , int , struct svc_req *);
#define PRODUCTO_ESCALAR 7
extern  float * producto_escalar_2(VectorNode , VectorNode , int , CLIENT *);
extern  float * producto_escalar_2_svc(VectorNode , VectorNode , int , struct svc_req *);
#define PRODUCTO_VECTORES 8
extern  VectorNode * producto_vectores_2(VectorNode , VectorNode , int , CLIENT *);
extern  VectorNode * producto_vectores_2_svc(VectorNode , VectorNode , int , struct svc_req *);
extern int calculadora_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA_VECTORES 5
extern  VectorNode * suma_vectores_2();
extern  VectorNode * suma_vectores_2_svc();
#define RESTA_VECTORES 6
extern  VectorNode * resta_vectores_2();
extern  VectorNode * resta_vectores_2_svc();
#define PRODUCTO_ESCALAR 7
extern  float * producto_escalar_2();
extern  float * producto_escalar_2_svc();
#define PRODUCTO_VECTORES 8
extern  VectorNode * producto_vectores_2();
extern  VectorNode * producto_vectores_2_svc();
extern int calculadora_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_VectorNode (XDR *, VectorNode*);
extern  bool_t xdr_VectorList (XDR *, VectorList*);
extern  bool_t xdr_sumar_1_argument (XDR *, sumar_1_argument*);
extern  bool_t xdr_restar_1_argument (XDR *, restar_1_argument*);
extern  bool_t xdr_multiplicar_1_argument (XDR *, multiplicar_1_argument*);
extern  bool_t xdr_dividir_1_argument (XDR *, dividir_1_argument*);
extern  bool_t xdr_suma_vectores_2_argument (XDR *, suma_vectores_2_argument*);
extern  bool_t xdr_resta_vectores_2_argument (XDR *, resta_vectores_2_argument*);
extern  bool_t xdr_producto_escalar_2_argument (XDR *, producto_escalar_2_argument*);
extern  bool_t xdr_producto_vectores_2_argument (XDR *, producto_vectores_2_argument*);

#else /* K&R C */
extern bool_t xdr_VectorNode ();
extern bool_t xdr_VectorList ();
extern bool_t xdr_sumar_1_argument ();
extern bool_t xdr_restar_1_argument ();
extern bool_t xdr_multiplicar_1_argument ();
extern bool_t xdr_dividir_1_argument ();
extern bool_t xdr_suma_vectores_2_argument ();
extern bool_t xdr_resta_vectores_2_argument ();
extern bool_t xdr_producto_escalar_2_argument ();
extern bool_t xdr_producto_vectores_2_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
