/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static float *
_sumar_1 (sumar_1_argument *argp, struct svc_req *rqstp)
{
	return (sumar_1_svc(argp->a, argp->b, rqstp));
}

static float *
_restar_1 (restar_1_argument *argp, struct svc_req *rqstp)
{
	return (restar_1_svc(argp->a, argp->b, rqstp));
}

static float *
_multiplicar_1 (multiplicar_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicar_1_svc(argp->a, argp->b, rqstp));
}

static float *
_dividir_1 (dividir_1_argument *argp, struct svc_req *rqstp)
{
	return (dividir_1_svc(argp->a, argp->b, rqstp));
}

static VectorNode *
_suma_vectores_2 (suma_vectores_2_argument *argp, struct svc_req *rqstp)
{
	return (suma_vectores_2_svc(argp->VectorA, argp->VectorB, argp->longitud, rqstp));
}

static VectorNode *
_resta_vectores_2 (resta_vectores_2_argument *argp, struct svc_req *rqstp)
{
	return (resta_vectores_2_svc(argp->VectorA, argp->VectorB, argp->longitud, rqstp));
}

static float *
_producto_escalar_2 (producto_escalar_2_argument *argp, struct svc_req *rqstp)
{
	return (producto_escalar_2_svc(argp->VectorA, argp->VectorB, argp->longitud, rqstp));
}

static VectorNode *
_producto_vectores_2 (producto_vectores_2_argument *argp, struct svc_req *rqstp)
{
	return (producto_vectores_2_svc(argp->VectorA, argp->VectorB, argp->longitud, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		sumar_1_argument sumar_1_arg;
		restar_1_argument restar_1_arg;
		multiplicar_1_argument multiplicar_1_arg;
		dividir_1_argument dividir_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMAR:
		_xdr_argument = (xdrproc_t) xdr_sumar_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _sumar_1;
		break;

	case RESTAR:
		_xdr_argument = (xdrproc_t) xdr_restar_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _restar_1;
		break;

	case MULTIPLICAR:
		_xdr_argument = (xdrproc_t) xdr_multiplicar_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _multiplicar_1;
		break;

	case DIVIDIR:
		_xdr_argument = (xdrproc_t) xdr_dividir_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _dividir_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calculadora_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_vectores_2_argument suma_vectores_2_arg;
		resta_vectores_2_argument resta_vectores_2_arg;
		producto_escalar_2_argument producto_escalar_2_arg;
		producto_vectores_2_argument producto_vectores_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_suma_vectores_2_argument;
		_xdr_result = (xdrproc_t) xdr_VectorNode;
		local = (char *(*)(char *, struct svc_req *)) _suma_vectores_2;
		break;

	case RESTA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_resta_vectores_2_argument;
		_xdr_result = (xdrproc_t) xdr_VectorNode;
		local = (char *(*)(char *, struct svc_req *)) _resta_vectores_2;
		break;

	case PRODUCTO_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_producto_escalar_2_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _producto_escalar_2;
		break;

	case PRODUCTO_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_producto_vectores_2_argument;
		_xdr_result = (xdrproc_t) xdr_VectorNode;
		local = (char *(*)(char *, struct svc_req *)) _producto_vectores_2;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CALCULADORA_SIMPLE);
	pmap_unset (CALCULADORA, CALCULADORA_VECTORES);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_SIMPLE, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_SIMPLE, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_VECTORES, calculadora_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_VECTORES, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_SIMPLE, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_SIMPLE, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_VECTORES, calculadora_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_VECTORES, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
